const BIG_JUMP_FORCE = 700;
const FALL_DEATH = 400;
const ENEMY_SPEED = 30;
const ENEMY_JUMP_FORCE = 200;
const BOSS_JUMP_FORCE = 600;
const BOSS_JUMP_TIME = 1;
const KAMINA_BOSS_JUMP_FORCE = 400;
const KAMINA_BOSS_JUMP_TIME = 3;
const GAME_MODE = 1; // 0 EASY 1 HARD
const MOVE_SPEED = GAME_MODE === 0 ? 300 : 170;
const JUMP_FORCE = GAME_MODE === 0 ? 600 : 415;
const DEV_MODE = true;

let isJumping = true;
let CURRENT_JUMP_FORCE = JUMP_FORCE;
let SOUND_STARTED = false;

module.exports = {
  BIG_JUMP_FORCE,
  FALL_DEATH,
  ENEMY_SPEED,
  ENEMY_JUMP_FORCE,
  BOSS_JUMP_FORCE,
  BOSS_JUMP_TIME,
  KAMINA_BOSS_JUMP_FORCE,
  KAMINA_BOSS_JUMP_TIME,
  MOVE_SPEED,
  DEV_MODE,
  isJumping,
  CURRENT_JUMP_FORCE,
  SOUND_STARTED,
};
